export default function QuotationPreview({ quotation }) {
  if (!quotation) return null;

  const advance = quotation.finalPrice ? Math.round(quotation.finalPrice * 0.4) : 0;

  const defaultInclusions = [
    'Quality stay',
    'Quality food (Breakfast + Dinner / MAP Plan)',
    'Experienced driver cum guide',
    `Private ${quotation.vehicleType || '[Vehicle Type]'}`,
    'Dedicated client support team',
  ];

  const defaultExclusions = [
    'Entry fees, permits, tickets',
    'Parking charges',
    'Lunch or any food outside package',
    'Anything not mentioned in inclusion',
  ];

  const inclusions = quotation.inclusions && quotation.inclusions.length > 0
    ? quotation.inclusions
    : defaultInclusions;

  const exclusions = quotation.exclusions && quotation.exclusions.length > 0
    ? quotation.exclusions
    : defaultExclusions;

  const itineraryText = quotation.itinerary && quotation.itinerary.length > 0
    ? quotation.itinerary.map((d) => `Day ${d.day}: ${d.description}`).join('\n')
    : quotation.itineraryLink || '[Paste Itinerary Link or Summary]';

  const text = `Form -1A || Quotation from PST

${quotation.tripDuration || '[Trip Duration]'} ${quotation.destination || '[Destination]'} Package trip with PSTourism™️, An ISO 9001:2015 certified travel company
Official website: www.pstourism.in

Traveller Details
Client Name: ${quotation.clientName}
Number of Pax: ${quotation.numberOfPax}
Number of Rooms: ${quotation.numberOfRooms || '[No. of Rooms]'}
Route / Pickup-Drop: (${quotation.route || '[Route]'})

Trip Itinerary
${itineraryText}

Package Pricing
Base Package Price: ₹ ${quotation.basePrice ? quotation.basePrice.toLocaleString('en-IN') : '[Amount]'}
Discount (if any): ₹ ${quotation.discount ? quotation.discount.toLocaleString('en-IN') : '0'}
Final Package Cost: ₹ ${quotation.finalPrice ? quotation.finalPrice.toLocaleString('en-IN') : '[Final Amount]'}

Booking and Payment Policy
40% Advance: ₹ ${advance.toLocaleString('en-IN')}
60% Payable after check-in on Day 1
Pay ₹ ${advance.toLocaleString('en-IN')} now to confirm your booking.

Inclusions
${inclusions.map((i) => `- ${i}`).join('\n')}

Exclusions
${exclusions.map((e) => `- ${e}`).join('\n')}

Know More About Us
About Us: https://www.pstourism.in/about-us
Google Reviews: https://maps.app.goo.gl/2iHbAFRBGeCRVwZi8
Explore Our Other Holiday Packages: https://www.pstourism.in/packages

Our Offices
Kolkata: Garia, Bidhan Pally, Near Gitanjali Metro, Kolkata – 700084
Bankura: Palasdanga, Bankura – 722208

Regards
Team PST
PSTourism™️ — Unlocking Your Premium Travel Experience`;
  const openHtmlPreview = () => {
    const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quotation - ${quotation.clientName}</title><style>body{font-family:Inter,system-ui,Arial;margin:20px;color:#123;} .header{background:linear-gradient(135deg,#102B3F,#1A4A6F);color:#fff;padding:28px;border-radius:12px;} .card{background:#fff;border-radius:12px;padding:18px;margin-top:18px;border:1px solid #e9edf2;} .btn{display:inline-block;padding:10px 14px;border-radius:8px;background:#0F5C7F;color:#fff;text-decoration:none;margin-right:8px}</style></head><body><div class="header"><h1>PST Quotation</h1><div>Package: ${quotation.destination || ''} — ${quotation.tripDuration || ''}</div></div><div class="card"><h3>Traveller Details</h3><p><strong>Client:</strong> ${quotation.clientName || ''}<br><strong>Contact:</strong> ${quotation.contact || ''}<br><strong>Pax:</strong> ${(quotation.adults||0)} Adult(s) ${(quotation.children?(', '+quotation.children+' Child(ren)'):'')}<br><strong>Rooms:</strong> ${quotation.numberOfRooms || '-'}<br><strong>Route:</strong> ${quotation.route || '-'}</p><h4>Cancellation Policy</h4><p>${quotation.cancellationPolicy || 'Standard cancellation policy applies.'}</p><h4>Itinerary</h4><p>${quotation.itineraryLink || '[Itinerary Link / Summary]'}</p><h4>Pricing</h4><p>Base: ₹ ${quotation.basePrice || '-'} <br> Discount: ₹ ${quotation.discount || 0} <br> Final: ₹ ${quotation.finalPrice || '-'} <br><strong>40% Advance: ₹ ${quotation.finalPrice ? Math.round(quotation.finalPrice*0.4) : 0}</strong></p><div style="display:flex;gap:12px;margin-top:12px;"><a class="btn" href="#" onclick="window.print();return false">Print / Save PDF</a></div></div><div class="card"><h4>Inclusions</h4><ul>${inclusions.map(i=>`<li>${i}</li>`).join('')} </ul><h4>Exclusions</h4><ul>${exclusions.map(e=>`<li>${e}</li>`).join('')}</ul></div><div style="margin-top:18px;font-size:12px;color:#556">This quotation is valid for 7 days. Generated by PSTourism</div></body></html>`;
    const w = window.open('', '_blank', 'noopener');
    if (!w) return alert('Popup blocked — allow popups for this site to preview');
    w.document.write(html);
    w.document.close();
  };

  return (
    <div className="card border-primary">
      <div className="card-header bg-primary text-white d-flex justify-content-between align-items-center">
        <span className="fw-bold"><i className="bi bi-file-earmark-text me-2"></i>Form-1A Preview</span>
        <div>
          <button className="btn btn-sm btn-light me-2" onClick={() => { navigator.clipboard.writeText(text); alert('Quotation text copied to clipboard!'); }}><i className="bi bi-copy me-1"></i>Copy Text</button>
          <button className="btn btn-sm btn-light" onClick={openHtmlPreview}><i className="bi bi-eye me-1"></i>Preview / Print</button>
        </div>
      </div>
      <div className="card-body">
        <pre className="mb-0" style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit', fontSize: '0.9rem', lineHeight: '1.6' }}>{text}</pre>
      </div>
    </div>
  );
}
