import { useState } from 'react';
import { useRouter } from 'next/router';
import Layout from '../../components/Layout';

export default function NewQuotation() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [form, setForm] = useState({
    clientName: '',
    contact: '',
    adults: '1',
    children: '0',
    numberOfRooms: '',
    roomType: 'Standard',
    route: '',
    cancellationPolicy: '',
    tripDuration: '',
    destination: '',
    itineraryLink: '',
    basePrice: '',
    discount: '0',
    finalPrice: '',
    vehicleType: '',
    inclusions: '',
    exclusions: '',
    status: 'Draft',
    notes: '',
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm((prev) => {
      const updated = { ...prev, [name]: value };
      if (name === 'basePrice' || name === 'discount') {
        const base = parseFloat(name === 'basePrice' ? value : prev.basePrice) || 0;
        const disc = parseFloat(name === 'discount' ? value : prev.discount) || 0;
        updated.finalPrice = String(base - disc);
      }
      return updated;
    });
  };

  const generateQuotationHTML = (data) => {
    const adults = Number(data.adults || 0);
    const children = Number(data.children || 0);
    const paxText = `${adults} Adult(s) ${children ? `, ${children} Child(ren)` : ''}`;
    const advance = data.finalPrice ? Math.round(Number(data.finalPrice) * 0.4) : 0;
    const inclusionsArr = Array.isArray(data.inclusions) ? data.inclusions : String(data.inclusions || '').split('\n').filter(Boolean);
    const exclusionsArr = Array.isArray(data.exclusions) ? data.exclusions : String(data.exclusions || '').split('\n').filter(Boolean);
    const inclusions = (inclusionsArr.length ? inclusionsArr : ['Quality stay']).map(i => `<li>${i}</li>`).join('');
    const exclusions = (exclusionsArr.length ? exclusionsArr : ['Entry fees, permits']).map(e => `<li>${e}</li>`).join('');
    return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quotation - ${data.clientName}</title><style>body{font-family:Inter,system-ui,Arial;margin:20px;color:#123;} .header{background:linear-gradient(135deg,#102B3F,#1A4A6F);color:#fff;padding:28px;border-radius:12px;} .card{background:#fff;border-radius:12px;padding:18px;margin-top:18px;border:1px solid #e9edf2;} .btn{display:inline-block;padding:10px 14px;border-radius:8px;background:#0F5C7F;color:#fff;text-decoration:none;margin-right:8px}</style></head><body><div class="header"><h1>PST Quotation</h1><div>Package: ${data.destination || ''} — ${data.tripDuration || ''}</div></div><div class="card"><h3>Traveller Details</h3><p><strong>Client:</strong> ${data.clientName || ''}<br><strong>Contact:</strong> ${data.contact || ''}<br><strong>Pax:</strong> ${paxText}<br><strong>Rooms:</strong> ${data.numberOfRooms || '-'}<br><strong>Route:</strong> ${data.route || '-'}</p><h4>Cancellation Policy</h4><p>${data.cancellationPolicy || 'Standard cancellation policy applies.'}</p><h4>Itinerary</h4><p>${data.itineraryLink || '[Itinerary Link / Summary]'}</p><h4>Pricing</h4><p>Base: ₹ ${data.basePrice || '-'} <br> Discount: ₹ ${data.discount || 0} <br> Final: ₹ ${data.finalPrice || '-'} <br><strong>40% Advance: ₹ ${advance}</strong></p><div style="display:flex;gap:12px;margin-top:12px;"><a class="btn" href="#" onclick="window.print();return false">Print / Save PDF</a></div></div><div class="card"><h4>Inclusions</h4><ul>${inclusions}</ul><h4>Exclusions</h4><ul>${exclusions}</ul></div><div style="margin-top:18px;font-size:12px;color:#556">This quotation is valid for 7 days. Generated by PSTourism</div></body></html>`;
  };

  const handlePreview = () => {
    const html = generateQuotationHTML(form);
    const w = window.open('', '_blank', 'noopener');
    if (!w) return alert('Popup blocked — allow popups for this site to preview');
    w.document.write(html);
    w.document.close();
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    const adults = Number(form.adults || 0);
    const children = Number(form.children || 0);
    const body = {
      ...form,
      adults,
      children,
      numberOfPax: adults + children,
      numberOfRooms: Number(form.numberOfRooms) || undefined,
      basePrice: Number(form.basePrice) || undefined,
      discount: Number(form.discount) || 0,
      finalPrice: Number(form.finalPrice) || undefined,
      inclusions: form.inclusions ? form.inclusions.split('\n').filter(Boolean) : [],
      exclusions: form.exclusions ? form.exclusions.split('\n').filter(Boolean) : [],
    };
    // include generated HTML version
    body.html = generateQuotationHTML(body);

    try {
      const res = await fetch('/api/quotations', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (data.success) {
        router.push(`/quotations/${data.data._id}`);
      } else {
        setError(data.error);
      }
    } catch (err) {
      setError('Failed to create quotation');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Layout title="New Quotation">
      <div className="d-flex align-items-center mb-4 flex-wrap gap-2">
        <button onClick={() => router.back()} className="btn btn-outline-secondary btn-sm me-1">
          <i className="bi bi-arrow-left me-1"></i>
          Back
        </button>
        <h2 className="mb-0 fw-bold d-flex align-items-center gap-2">
          <span className="section-icon"><i className="bi bi-file-earmark-text"></i></span>
          New Quotation
        </h2>
      </div>

      {error && <div className="alert alert-danger">{error}</div>}

      <form onSubmit={handleSubmit}>
        <div className="row g-4">
          {/* Client Details */}
          <div className="col-12">
            <div className="card shadow-sm">
              <div className="card-header bg-primary text-white">
                <h6 className="mb-0"><i className="bi bi-person-vcard me-2"></i>Client Details</h6>
              </div>
              <div className="card-body">
                <div className="row g-3">
                  <div className="col-md-6">
                    <label className="form-label">Client Name *</label>
                    <input type="text" className="form-control" name="clientName" value={form.clientName} onChange={handleChange} required />
                  </div>
                  <div className="col-md-6">
                    <label className="form-label">Contact</label>
                    <input type="text" className="form-control" name="contact" value={form.contact} onChange={handleChange} />
                  </div>
                  <div className="col-12">
                    <label className="form-label">Number of Pax</label>
                  </div>
                  <div className="col-md-4">
                    <label className="form-label">How many Adults *</label>
                    <input type="number" className="form-control" name="adults" value={form.adults} onChange={handleChange} required min="0" />
                  </div>
                  <div className="col-md-4">
                    <label className="form-label">How many Childs</label>
                    <input type="number" className="form-control" name="children" value={form.children} onChange={handleChange} min="0" />
                  </div>
                  <div className="col-md-4">
                    <label className="form-label">Number of Rooms</label>
                    <input type="number" className="form-control" name="numberOfRooms" value={form.numberOfRooms} onChange={handleChange} min="1" />
                  </div>
                  <div className="col-md-4">
                    <label className="form-label">Room Type</label>
                    <select className="form-select" name="roomType" value={form.roomType} onChange={handleChange}>
                      <option>Standard</option>
                      <option>Deluxe</option>
                      <option>Premium</option>
                    </select>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Trip Details */}
          <div className="col-12">
            <div className="card shadow-sm">
              <div className="card-header bg-success text-white">
                <h6 className="mb-0"><i className="bi bi-geo-alt me-2"></i>Trip Details</h6>
              </div>
              <div className="card-body">
                <div className="row g-3">
                  <div className="col-md-6">
                    <label className="form-label">Destination</label>
                    <input type="text" className="form-control" name="destination" value={form.destination} onChange={handleChange} placeholder="e.g. Sikkim, Darjeeling" />
                  </div>
                  <div className="col-md-6">
                    <label className="form-label">Trip Duration</label>
                    <input type="text" className="form-control" name="tripDuration" value={form.tripDuration} onChange={handleChange} placeholder="e.g. 5 Nights / 6 Days" />
                  </div>
                  <div className="col-md-6">
                    <label className="form-label">Route / Pickup-Drop</label>
                    <input type="text" className="form-control" name="route" value={form.route} onChange={handleChange} placeholder="e.g. NJP-NJP or Kolkata-Kolkata" />
                  </div>
                  <div className="col-md-6">
                    <label className="form-label">Vehicle Type</label>
                    <input type="text" className="form-control" name="vehicleType" value={form.vehicleType} onChange={handleChange} placeholder="e.g. Innova Crysta, Tempo Traveller" />
                  </div>
                  <div className="col-12">
                    <label className="form-label">Itinerary Link</label>
                    <input type="url" className="form-control" name="itineraryLink" value={form.itineraryLink} onChange={handleChange} placeholder="https://..." />
                  </div>
                  <div className="col-12">
                    <label className="form-label">Cancellation Policy</label>
                    <textarea className="form-control" name="cancellationPolicy" value={form.cancellationPolicy} onChange={handleChange} rows="3" placeholder="E.g. 25% refund up to 15 days before..." />
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Pricing */}
          <div className="col-12">
            <div className="card shadow-sm">
              <div className="card-header bg-warning text-dark">
                <h6 className="mb-0"><i className="bi bi-cash-coin me-2"></i>Pricing</h6>
              </div>
              <div className="card-body">
                <div className="row g-3">
                  <div className="col-md-4">
                    <label className="form-label">Base Package Price (₹)</label>
                    <input type="number" className="form-control" name="basePrice" value={form.basePrice} onChange={handleChange} min="0" />
                  </div>
                  <div className="col-md-4">
                    <label className="form-label">Discount (₹)</label>
                    <input type="number" className="form-control" name="discount" value={form.discount} onChange={handleChange} min="0" />
                  </div>
                  <div className="col-md-4">
                    <label className="form-label">Final Price (₹)</label>
                    <input type="number" className="form-control" name="finalPrice" value={form.finalPrice} onChange={handleChange} min="0" />
                  </div>
                  {form.finalPrice && (
                    <div className="col-12">
                      <div className="alert alert-info mb-0">
                        <strong>40% Advance: ₹{Math.round(Number(form.finalPrice) * 0.4).toLocaleString('en-IN')}</strong>
                        <span className="ms-3 text-muted">Balance (60%): ₹{Math.round(Number(form.finalPrice) * 0.6).toLocaleString('en-IN')}</span>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Inclusions & Exclusions */}
          <div className="col-md-6">
            <div className="card shadow-sm h-100">
              <div className="card-header bg-success text-white">
                <h6 className="mb-0"><i className="bi bi-check2-circle me-2"></i>Inclusions</h6>
              </div>
              <div className="card-body">
                <textarea
                  className="form-control"
                  name="inclusions"
                  value={form.inclusions}
                  onChange={handleChange}
                  rows="6"
                  placeholder="One item per line&#10;Quality stay&#10;Quality food (MAP Plan)&#10;..."
                />
                <small className="text-muted">Leave blank for default inclusions</small>
              </div>
            </div>
          </div>

          <div className="col-md-6">
            <div className="card shadow-sm h-100">
              <div className="card-header bg-danger text-white">
                <h6 className="mb-0"><i className="bi bi-x-circle me-2"></i>Exclusions</h6>
              </div>
              <div className="card-body">
                <textarea
                  className="form-control"
                  name="exclusions"
                  value={form.exclusions}
                  onChange={handleChange}
                  rows="6"
                  placeholder="One item per line&#10;Entry fees, permits&#10;Parking charges&#10;..."
                />
                <small className="text-muted">Leave blank for default exclusions</small>
              </div>
            </div>
          </div>

          {/* Status & Notes */}
          <div className="col-12">
            <div className="card shadow-sm">
              <div className="card-header bg-secondary text-white">
                <h6 className="mb-0">⚙️ Settings</h6>
              </div>
              <div className="card-body">
                <div className="row g-3">
                  <div className="col-md-4">
                    <label className="form-label">Status</label>
                    <select className="form-select" name="status" value={form.status} onChange={handleChange}>
                      <option>Draft</option>
                      <option>Sent</option>
                      <option>Accepted</option>
                      <option>Rejected</option>
                    </select>
                  </div>
                  <div className="col-md-8">
                    <label className="form-label">Internal Notes</label>
                    <textarea className="form-control" name="notes" value={form.notes} onChange={handleChange} rows="2" />
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="col-12">
            <button type="submit" className="btn btn-primary btn-lg me-2" disabled={loading}>
              {loading ? <><span className="spinner-border spinner-border-sm me-2" />Saving...</> : <><i className="bi bi-floppy me-2"></i>Create Quotation</>}
            </button>
            <button type="button" className="btn btn-outline-secondary btn-lg me-2" onClick={handlePreview}>
              <i className="bi bi-eye me-2"></i>Preview Quotation
            </button>
            <div style={{display:'inline-block',verticalAlign:'middle',marginLeft:8}}>
              <label className="form-check-label me-2"><input type="checkbox" className="form-check-input me-1" name="sendToLead" onChange={(e)=>setForm(prev=>({...prev, sendToLead: e.target.checked}))} /> Send to Lead</label>
              <label className="form-check-label ms-2"><input type="checkbox" className="form-check-input me-1" name="sendToTravellers" onChange={(e)=>setForm(prev=>({...prev, sendToTravellers: e.target.checked}))} /> Send to Travellers</label>
            </div>
            <button type="button" className="btn btn-outline-secondary btn-lg" onClick={() => router.back()}>
              Cancel
            </button>
          </div>
        </div>
      </form>
    </Layout>
  );
}
